services:

  - type: web
    name: shelfhelp
    runtime: static
    repo: https://github.com/MCBoarder289/shelf-help
    branch: main
    envVars:
    - key: SKIP_INSTALL_DEPS
      value: true
    buildCommand: yarn; yarn build
    staticPublishPath: dist
    routes:
    - type: rewrite
      source: /bookChoices
      destination: https://shelfhelp-api.onrender.com/bookChoices
    - type: rewrite
      source: /libraryCheck
      destination: https://shelfhelp-api.onrender.com/libraryCheck
    rootDir: frontend
    pullRequestPreviewsEnabled: true

  - type: web
    name: shelfhelp-api
    runtime: python
    repo: https://github.com/MCBoarder289/shelf-help
    branch: main
    plan: free
    envVars:
    - key: PYTHON_VERSION
      value: 3.12.3
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config geventlet-config.py --workers=1 --worker-class=gevent app:app -t 60 --keep-alive 60
    rootDir: backend
    pullRequestPreviewsEnabled: true

  - type: web
    name: shelfhelpanalytics
    runtime: static
    repo: https://github.com/MCBoarder289/shelf-help
    branch: main
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
    buildCommand: yarn; yarn build
    staticPublishPath: dist
    rootDir: analytics/app
    pullRequestPreviewsEnabled: true

version: "1"