INSERT INTO libraries (library_id, library_name) VALUES
('nashville', 'Nashville Public Library'),
('mdpls', 'Miami-Dade Public Library System'),
('onlib', 'Syracuse, NY (Onondaga County Public Library)'),
('clc', 'Columbus, OH (Digital Downloads Collaboration)'),
('cincinnatilibrary', 'Cincinnati & Hamilton County Public Library'),
('sfpl', 'San Francisco Public Library'),
('phoenix', 'Greater Phoenix Digital Library'),
('wplc', 'Delafield (Wisconsin Public Library Consortium)'),
('toledo', 'Toledo Lucas County Public Library'),
('lapl', 'Los Angeles Public Library'),
('sno-isle', 'Sno-Isle Libraries'),
('pueblolibrary', 'Pueblo City-County Library District'),
('nlb', 'National Library Board Singapore'),
('livebrary', 'Livebrary.com'),
('clevnet', 'CLEVNET'),
('kcls', 'King County Library System'),
('auckland', 'Auckland Libraries'),
('ppld', 'Pikes Peak Library District'),
('toronto', 'Toronto Public Library'),
('indypl', 'Indianapolis Public Library'),
('melsa', 'MELSA: Twin Cities Metro eLibrary'),
('metrolibrary', 'Metropolitan Library System'),
('brooklyn', 'Brooklyn Public Library'),
('connors', 'Connors State College'),
('ocln', 'Old Colony Library Network'),
('nypl', 'New York Public Library'),
('ohdbks', 'The Ohio Digital Library'),
('babsonedu', 'Babson College'),
('idl', 'Indiana Digital Library'),
('lasvegas', 'Las Vegas-Clark County Library District'),
('multcolib', 'Multnomah County Library'),
('saclibrary', 'Sacramento Public Library'),
('hcpl', 'Harris County Public Library'),
('austinlibrary', 'Austin Public Library'),
('surly', 'Student Union Recreational Library, SURLY MSA'),
('spl', 'Seattle Public Library'),
('hcplc', 'Hillsborough County Public Library Cooperative'),
('riezone', 'Ocean State Libraries eZone'),
('arapahoe', 'Arapahoe Library District'),
('piercecounty', 'Pierce County Library System'),
('mcpl', 'Mid-Continent Public Library'),
('wccls', 'Washington County Cooperative Library Services'),
('baileylibrary', 'Bailey Public Library'),
('sails', 'SAILS Library Network'),
('ocls', 'Orange County Library System'),
('bpl', 'Boston Public Library'),
('lacountylibrary', 'LA County Library'),
('aclib', 'Alachua County Library District'),
('dayton', 'Dayton Metro Library'),
('ccpl', 'Cuyahoga County Public Library'),
('houstonlibrary', 'Houston Public Library'),
('ebr', 'East Baton Rouge Parish Library'),
('calgary', 'Calgary Public Library'),
('sdcl', 'San Diego County Library'),
('lfpl', 'Louisville Free Public Library'),
('commerceca', 'City of Commerce Public Library'),
('midcolumbialibraries', 'Mid-Columbia Libraries'),
('acla', 'Carnegie Library of Pittsburgh'),
('scld', 'Spokane County Library District'),
('lcls', 'Lee County Library System'),
('minuteman', 'Minuteman Library Network'),
('neworleans', 'New Orleans Public Library'),
('timberland', 'Timberland Regional Library'),
('queenslibrary', 'Queens Public Library'),
('slco', 'Salt Lake County Library Services'),
('epl', 'Edmonton Public Library'),
('sanantonio', 'San Antonio Public Library'),
('dallaslibrary', 'Dallas Public Library'),
('beehive', 'Beehive Library Consortium'),
('kyunbound', 'Kentucky Libraries Unbound'),
('santaclara', 'Santa Clara County Library'),
('markham', 'Markham Public Library'),
('jpl', 'Jacksonville Public Library'),
('slcl', 'St. Louis County Library'),
('voebb', 'Berlin, Verbund Öffentlicher Bibliotheken (VÖBB)'),
('pioneerok', 'Pioneer Library System'),
('cwmars', 'CW MARS'),
('reads', 'Tennessee READS'),
('saskatchewan', 'Saskatchewan Library Consortium'),
('ccc', 'Contra Costa County Library'),
('kdl', 'Kent District Library'),
('ocpl', 'OC Public Libraries'),
('surreyca', 'Surrey Libraries'),
('christchurch', 'Christchurch City Libraries'),
('hpl', 'Hamilton Public Library'),
('fresno', 'Fresno County Public Library'),
('ncdigital', 'North Carolina Digital Library'),
('sonoma', 'Sonoma County Library'),
('cals', 'Central Arkansas Library System'),
('lakecounty', 'Lake County Public Library'),
('freelibrary', 'The Free Library of Philadelphia'),
('serra', 'Serra Cooperative Library System'),
('westchester', 'Westchester Library System'),
('sanjose', 'San Jose Public Library'),
('adlc', 'Arkansas Digital Library Consortium'),
('evpl', 'Evansville Vanderburgh Public Library'),
('dlil', 'Digital Library of Illinois'),
('nmls', 'Nicholson Memorial Library System'),
('goldcoast', 'Gold Coast Libraries'),
('denver', 'Denver Public Library'),
('fwpl', 'Fort Worth Public Library'),
('bridges', 'Bridges'),
('odmc', 'Ontario Library Service Consortium'),
('hawaii', 'Hawaii State Public Library System'),
('akronlibrary', 'Akron-Summit County Public Library'),
('inglewoodpl', 'Inglewood Public Library'),
('pls', 'Peninsula Library System'),
('pima', 'Pima County Public Library'),
('aclibrary', 'Alameda County Library'),
('mlc', 'Midwest Collaborative for Library Services'),
('tscpl', 'Topeka and Shawnee County Public Library'),
('tlc', 'The Libraries Consortium'),
('wvdeli', 'West Virginia Downloadable Entertainment Library Initiative'),
('ottawa', 'Ottawa Public Library'),
('sapln', 'South Australian Public Library Network'),
('anythinklibraries', 'Rangeview Library District'),
('cabq', 'Albuquerque Bernalillo County Library System'),
('myrl', 'Richland Library'),
('nassau', 'Nassau Digital Doorway'),
('kenton', 'Kenton County Public Library'),
('broward', 'Broward County Library'),
('northnet', 'NorthNet Library System'),
('alhambralibrary', 'Alhambra Civic Center Library'),
('naperville', 'Naperville Public Library'),
('buffalo', 'Buffalo & Erie County Public Library'),
('anytime', 'Washington Anytime Library'),
('jclc', 'Jefferson County Library Cooperative'),
('dclibrary', 'District of Columbia Public Library'),
('acpl', 'Allen County Public Library'),
('yourlibrary', 'Your Library'),
('kclibrary', 'Kansas City Public Library'),
('sbcldigital', 'San Bernardino County Library'),
('omnilibraries', 'Online Media of Northern Illinois Libraries'),
('dod', 'Department of Defense'),
('tulsa', 'Tulsa City-County Library'),
('chipublib', 'Chicago Public Library'),
('vpl', 'Vancouver Public Library'),
('mediaondemand', 'Media On Demand'),
('fortvancouver', 'Fort Vancouver Regional Library District'),
('slcpl', 'Salt Lake City Public Library'),
('lsw', 'Libraries Southwest Consortium'),
('sjcpl', 'St. Joseph County Public Library'),
('henrico', 'Henrico County Public Library'),
('emedialibrary', 'eMediaLibrary'),
('fairfax', 'Fairfax County Public Library'),
('plano', 'Plano Public Library System'),
('sunflowerelibrary', 'Sunflower eLibrary'),
('arlington', 'Arlington Public Library'),
('dcl', 'Douglas County Libraries'),
('jocolibrary', 'Johnson County Library and Olathe Public Library'),
('pgcmls', 'Prince George''s County Memorial Library System'),
('jeff', 'Jefferson Parish Library'),
('memphis', 'Memphis Public Libraries'),
('stcharles', 'St. Charles City-County Library District'),
('virtuallibrary', 'Virtual Library of Wyoming'),
('krl', 'Kitsap Regional Library'),
('okvirtuallibrary', 'OK Virtual Library'),
('wvreads', 'West Virginia Reads'),
('tln', 'Download Destination'),
('thegdl', 'Genesee District Library'),
('library2go', 'Oregon Digital Library Consortium'),
('librariestasmania', 'Libraries Tasmania'),
('oakland', 'Oakland Public Library'),
('mcplmd', 'Montgomery County Public Libraries'),
('halifax', 'Halifax Public Libraries'),
('dbrl', 'Daniel Boone Regional Library'),
('nebraska', 'Nebraska OverDrive Libraries'),
('mississauga', 'Mississauga Library'),
('monmouth', 'Monmouth County Library'),
('uhls', 'Upper Hudson Library System'),
('marinet', 'MARINet'),
('wcl', 'Wellington City Libraries'),
('fulcolibrary', 'Fulton County Library System'),
('mvlc', 'Merrimack Valley Library Consortium'),
('omaha', 'Omaha Public Library'),
('lakeland', 'Lakeland Digital Library'),
('orl', 'Okanagan Regional Library'),
('arrowhead', 'Arrowhead Library System'),
('wapldmc', 'Western Australia Public Libraries'),
('plcmc', 'Charlotte Mecklenburg Library'),
('greenwich', 'Greenwich Library'),
('molib2go', 'Missouri Libraries 2Go'),
('frontrange', 'Front Range Downloadable Library'),
('greengoldlibraries', 'Green Gold Consortium'),
('sjcpls', 'St. Johns County Public Library'),
('jefferson', 'Jefferson County Public Library'),
('marmot', 'Marmot Library Network'),
('dpls', 'Deschutes Public Library'),
('rochester', 'Rochester Public Library'),
('spartanburglibraries', 'Spartanburg County Public Libraries'),
('burnaby', 'Burnaby Public Library'),
('lincoln', 'Lincoln City Libraries'),
('libraryweb', 'Monroe County Library System'),
('gvpl', 'Greater Victoria Public Library'),
('noble', 'NOBLE: North of Boston Library Exchange'),
('mmlc', 'Mideastern Michigan Library Cooperative'),
('bcplinfo', 'Baltimore County Public Library'),
('elm', 'eLibraries Manitoba'),
('brisbane', 'Brisbane City Council Library Services'),
('slpl', 'St. Louis Public Library'),
('yvl', 'Yakima Valley Libraries'),
('downloadlibrary', 'downloadLibrary'),
('carmel', 'Carmel Clay Public Library'),
('id8', 'LYNX Library Consortium'),
('grpl', 'Grand Rapids Public Library'),
('boise', 'Boise Public Library'),
('clamsnet', 'CLAMS'),
('ndlibrary2go', 'North Dakota Digital Consortium'),
('youngstown', 'The Public Library of Youngstown and Mahoning County'),
('yln', 'Yavapai Library Network'),
('winnipeg', 'Winnipeg Public Library'),
('ifpl', 'Idaho Falls Public Library'),
('metronet', 'Metro Net Library Consortium'),
('lexpublib', 'Lexington Public Library'),
('berkeleypubliclibrary', 'Berkeley Public Library'),
('dekalb', 'DeKalb County Public Library'),
('elibrarynj', 'eLibrary NJ'),
('hadc', 'Houston Area Digital Media Catalog'),
('washoecounty', 'Washoe County Library System'),
('camellia', 'Camellia Net Digital Catalog'),
('chester', 'Chester County Library System'),
('ebccls', 'Bergen County Cooperative Library System'),
('selco', 'Southeastern Libraries Cooperating'),
('lcpl', 'Loudoun County Public Library'),
('irvinglibrary', 'Irving Public Library'),
('yourlibraryca', 'Richmond Public Library'),
('neflin', 'NEFLIN'),
('lpl', 'London Public Library'),
('hcplibrary', 'Hancock County Public Library'),
('jasmine', 'South Carolina Low Country Consortium'),
('brevard', 'Brevard County Library'),
('fvrl', 'Fraser Valley Regional Library'),
('svlc', 'Southwest Valley Library Consortium'),
('chesterfield', 'Chesterfield County Public Library'),
('lib2go', 'ArkansasLibrary2Go'),
('moretonbay', 'Moreton Bay Libraries'),
('bhpl', 'Beverly Hills Public Library'),
('pclc', 'Polk County Library Cooperative'),
('arlingtontx', 'Arlington Public Library'),
('solano', 'Solano County Library'),
('somerset', 'Somerset County Library System'),
('trac', 'TRAC Consortium'),
('spokanelibrary', 'Spokane Public Library'),
('balibrary', 'Barrington Area Library'),
('e-inc', 'E-iNC Library'),
('vbpl', 'Virginia Beach Public Library'),
('gmlc', 'Green Mountain Library Consortium'),
('rcls', 'Ramapo Catskill Library System'),
('aubora', 'Aubora OverDrive'),
('swvapub', 'Southwest Virginia Public Libraries'),
('montana', 'MontanaLibrary2Go'),
('banq', 'Bibliothèque et Archives nationales du Québec'),
('elpaso', 'El Paso Public Library'),
('sheppardnc', 'Sheppard Memorial Library'),
('gadd', 'Georgia Download Destination'),
('blackgold', 'Black Gold Cooperative Library System'),
('kent', 'Kent County Council'),
('andersonlibrary', 'Anderson County Library'),
('icpl', 'Digital Johnson County'),
('durhamcounty', 'Durham County Library'),
('tempe', 'Tempe Public Library'),
('parralibrary', 'City of Parramatta Library'),
('burlington', 'Burlington County Library System'),
('bcpl', 'British Columbia Libraries'),
('cobbcounty', 'Cobb County Public Library System'),
('panhandle', 'Panhandle Library Access Network'),
('boroondara', 'Boroondara Library Service'),
('lamb', 'New Castle District Library Center'),
('frisco', 'Frisco Public Library'),
('santaclarita', 'City of Santa Clarita Public Library'),
('nsdc', 'North Suburban Digital Consortium'),
('sclibrary', 'Strathcona County Library'),
('charlestoncounty', 'Charleston County Public Library System'),
('adl', 'Alaska Digital Library'),
('norfolk', 'Norfolk County Council'),
('maryland', 'Maryland''s Digital Library'),
('lbpl', 'Long Beach Public Library'),
('rdpl', 'Red Deer Public Library'),
('fukuyama-library', 'Fukuyama City Library'),
('ncdl', 'Northern California Digital Library'),
('elnb-bnnb', 'Bibliothèques publiques du N.-B. / New Brunswick Public Libraries'),
('nckids', 'NC Kids Digital Library'),
('greenvillesc', 'Greenville County Library System'),
('ecrl', 'East Central Regional Library'),
('ecoop', 'E-Library Co-Op of Southeast Louisiana'),
('tadl', 'Traverse Area District Library'),
('aurorapubliclibrary', 'Aurora Public Library District'),
('southdakota', 'South Dakota Digital Consortium'),
('epukapuka', 'Lower North Island'),
('pinnacle', 'Pinnacle Digital Consortium'),
('skokielibrary', 'Skokie Public Library'),
('mainlib', 'Main Library Alliance'),
('infoway', 'Farmington Public Library'),
('owwl', 'OWWL Library System'),
('delaware', 'Delaware Libraries'),
('montcolibs', 'Montgomery County Library District Consortium'),
('rhpl', 'Richmond Hill Public Library'),
('meridian', 'Meridian Library District'),
('delco', 'Delaware County Library System'),
('lplelibrary', 'Laredo Public Library'),
('greaterdandenong', 'Greater Dandenong Libraries'),
('upnorth', 'Up North Michigan Consortium'),
('tacoma', 'Tacoma Public Library'),
('ajax', 'Ajax Public Library'),
('cvl', 'Chattahoochee Valley Libraries'),
('ncwlibraries', 'NCW Libraries'),
('wichita', 'Wichita Public Library'),
('pplc', 'Pinellas Public Library Cooperative'),
('dmpl', 'Des Moines Public Library'),
('mellansjo', 'Bibliotek Mellansjö'),
('martin', 'Martin County Public Library'),
('narita-public-library', 'Narita Public Library'),
('sttammany', 'St. Tammany Parish Library'),
('maltalibraries', 'Malta Libraries'),
('nh', 'New Hampshire State Library'),
('biboroughuk', 'Kensington & Chelsea and Westminster Libraries'),
('poudre', 'Poudre River Public Library District'),
('jericholibrary', 'Jericho Public Library'),
('capitalarealibrary', 'Capital Area Library District'),
('springfield', 'Springfield-Greene County Library'),
('ocl', 'Ocean County Library'),
('yuma', 'Yuma County Library District'),
('netldc', 'Northeast Texas Digital Consortium'),
('kern', 'Kern County Library'),
('hkpl', 'Hong Kong Public Libraries (HKPL)'),
('ayabe-library', 'Ayabe City Library'),
('brdc', 'Blue Ridge Download Consortium'),
('wrl', 'Williamsburg Regional Library'),
('glllibraries', 'Better Libraries Digital Consortium'),
('stls', 'Southern Tier Library System'),
('bigcountry', 'Big Country Library System'),
('vastraskaraborg', 'Bibliotek Västra Skaraborg'),
('hepl', 'Hamilton East Public Library'),
('librarypoint', 'Central Rappahannock Regional Library'),
('ak', 'Arbeiterkammer'),
('aurora', 'Aurora Public Library'),
('mercedcountylibrary', 'Merced County Library'),
('edownload', 'Lambton County Library'),
('brunswickcounty', 'Brunswick County Library'),
('siouxlndsd', 'Siouxland Libraries'),
('burlingtonpl', 'Burlington Public Library'),
('tuscaloosa', 'Tuscaloosa Public Library'),
('wakegov', 'Wake County Public Libraries'),
('libraryconnection', 'Library Connection, Inc.'),
('flls', 'Finger Lakes Library System'),
('shortgrass', 'Shortgrass Library System'),
('lincolnshirelibraries', 'Lincolnshire Libraries'),
('citrus', 'Citrus County Library System'),
('blackhills', 'Black Hills Library Digital Consortium'),
('westbanklibrary', 'Westbank Community Library District'),
('gotlib', 'Biblioteken i Göteborg'),
('midyork', 'Mid-York Library System'),
('larl', 'Lake Agassiz Regional Library'),
('fuelyourmind', 'White Pine Library Cooperative'),
('oxfordshire', 'Oxfordshire County Council'),
('lex', 'Lexington County Public Library System'),
('alliance', 'Alliance Digital Media Library'),
('yprl', 'Yarra Plenty Regional Library'),
('myjdl', 'Jackson District Library'),
('forsyth', 'Forsyth County Public Library'),
('iredell', 'Iredell County Library'),
('buckinghamshire', 'Buckinghamshire Council'),
('whitby', 'Whitby Public Library'),
('elibrary', 'Newfoundland & Labrador Public Libraries'),
('mhls', 'Mid-Hudson Library System'),
('librariesniuk', 'Libraries NI'),
('ctdl', 'Central Texas Digital Consortium'),
('ageo-city-library', 'Ageo City Library'),
('sovalue', 'Southern Virginia Libraries United Electronically'),
('novascotia-annapolisvalley', 'Same Page Libraries'),
('novascotia-westerncounties', 'Same Page Libraries'),
('samepage', 'Same Page Libraries'),
('coloradodc', 'Across Colorado Digital Consortium'),
('oceancity', 'Ocean City Free Public Library'),
('mlcstl', 'Municipal Library Consortium of St. Louis County'),
('norfolk-va', 'Norfolk Public Library'),
('princewilliam', 'Prince William Public Library System'),
('brantford', 'Brantford Public Library'),
('hendersonlibraries', 'Henderson Libraries'),
('ryde', 'City of Ryde Library'),
('everett', 'Everett Public Library'),
('birmingham-uk', 'Birmingham Libraries'),
('alexandria', 'Alexandria Library'),
('scdl', 'Southern California Digital Library'),
('virl', 'Vancouver Island Regional Library'),
('brightonhovegb', 'Brighton & Hove City Libraries'),
('harnosand', 'Harnosands Bibliotek'),
('santamonica', 'Santa Monica Public Library'),
('solna', 'Solna Stadsbibliotek'),
('ebranch2go', 'eBranch2Go'),
('rpls', 'Rolling Prairie Digital Consortium'),
('lawrencepl', 'Lawrence Public Library'),
('chinookarch', 'Chinook Arch Regional Library System'),
('essexca', 'Essex County Library'),
('lavergnelibrary', 'La Vergne Public Library'),
('princetonlibrary', 'Princeton Public Library'),
('woodlands', 'Woodlands Downloadable Library'),
('ujicity-library', 'Uji City Library'),
('alingsas', 'Alingsås Library'),
('gwinnett', 'Gwinnett County Public Library'),
('tblc', 'Tampa Bay Library Consortium'),
('yclibrary', 'York County Library'),
('lion', 'LION: Libraries Online'),
('southtexas', 'South Texas Library System'),
('keyslibraries', 'Monroe County Public Library'),
('vaughanpl', 'Vaughan Public Libraries'),
('badico', 'Bayern Digital Consortium'),
('elibraryhh', 'Bücherhallen Hamburg'),
('shinshu-kyodo-library', 'Digi Tosho Shinshu'),
('ssjcpl', 'Stockton-San Joaquin County Public Library'),
('dundeecity', 'Leisure and Culture Dundee'),
('wml', 'Whitehorse Manningham Regional Library Corporation'),
('lincsinspireuk', 'Lincs Inspire Libraries'),
('kirklees', 'Kirklees Libraries'),
('ylpl', 'Yorba Linda Public Library'),
('surreycountyuk', 'Surrey County Council'),
('hornsby', 'Hornsby Shire Library & Information Service'),
('sabah', 'Sabah State Library'),
('hancock', 'Hancock County Library System'),
('logan', 'Logan City Council'),
('ntrls', 'North Texas Libraries on the Go'),
('mohave', 'Mohave County Library District'),
('northernbeacheslibraries', 'Northern Beaches Libraries'),
('semcofl', 'Seminole County Public Library System'),
('idahodigital', 'Idaho Digital Consortium'),
('fortbend', 'Fort Bend County Libraries'),
('mrspl', 'Mary Riley Styles Public Library'),
('mooneevalley', 'Moonee Valley Libraries'),
('darien', 'Darien Library'),
('highplains', 'High Plains Library District'),
('fullerton', 'Fullerton Public Library'),
('cityoflondonuk', 'City of London Libraries'),
('centralpalibraries', 'Central PA Libraries'),
('reading', 'Reading District Libraries'),
('sheffielduk', 'Sheffield Libraries'),
('gldl', 'Great Lakes Digital Libraries'),
('tolibrary', 'Thousand Oaks Library System'),
('scenicregional', 'Scenic Regional Library'),
('nepadl', 'Northeast Pennsylvania Digital Library'),
('bartowlibrary', 'Bartow County Library System'),
('wpl', 'Westchester Public Library'),
('salinaspubliclibrary', 'Salinas Public Library'),
('rvl', 'Roanoke Valley Libraries'),
('listeneasternwv', 'Listen Eastern West Virginia'),
('suffolklibraries', 'Suffolk Libraries'),
('avalonfreelibrary', 'Avalon Free Public Library'),
('westtexas', 'West Texas Digital Consortium'),
('cldl', 'Carbon Lehigh Downloadable Library'),
('obihirocity', 'Obihiro City Library'),
('penrith', 'Penrith City Library'),
('morayuk', 'Moray Libraries'),
('prl', 'Pamunkey Regional Library'),
('bibliotecacomfandi', 'Comfandi'),
('yolocounty', 'Yolo County Library'),
('sunnyvale', 'Sunnyvale Public Library'),
('santabarbara', 'Santa Barbara Public Library'),
('flint', 'Gloria Coles Flint Public Library'),
('mobius', 'MOBIUS Consortium'),
('barnet', 'London Borough of Barnet'),
('sutherland', 'Sutherland Shire Council'),
('redlandqld', 'Redland City Library Service'),
('cabconc', 'Cabarrus County Public Library'),
('pwdl', 'Piney Woods Digital Consortium'),
('harryda', 'Biblioteken i Härryda kommun'),
('sapl', 'St. Albert Public Library'),
('silverstarcoop', 'Nevada Library Cooperative'),
('ccls', 'Chautauqua-Cattaraugus Library System'),
('unioncounty', 'Union County Library'),
('princeton', 'Princeton University'),
('dubuque', 'Carnegie-Stout Public Library'),
('ycl', 'York County Libraries'),
('livuni', 'University of Liverpool'),
('volusia', 'Volusia County Public Library'),
('tgclibrary', 'Tom Green County Library System'),
('aberdeenshirelibraries', 'Aberdeenshire Library and Information Service'),
('nm', 'New Mexico Library To Go'),
('britishcouncil', 'British Council Libraries Consortium'),
('mcgill', 'McGill University Library'),
('cin', 'Cooperative Information Network'),
('dlrcoco', 'Dun Laoghaire-Rathdown County Council Public Library Service'),
('detroitpubliclibrary', 'Detroit Public Library'),
('mvls', 'Mohawk Valley Library System'),
('eodls', 'Eastern Oklahoma Library System'),
('fremont', 'Fremont Public Library'),
('idea', 'IDEA by ICfL'),
('glasgow', 'Glasgow Libraries'),
('bibliomontreal', 'Bibliothèques Montréal'),
('bibliomation', 'Bibliomation, Inc.'),
('lonestardigitalibrary', 'Lone Star Digital Library'),
('richmondpubliclibrary', 'Richmond Public Library'),
('smdl', 'Southwest Michigan Digital Library'),
('ebonnerlibrary', 'East Bonner County Library District'),
('santaanapubliclibrary', 'Santa Ana Public Library'),
('ereolenglobal', 'eReolen Global'),
('camdigital', 'Camarillo Public Library'),
('leicesteruk', 'Leicester Libraries'),
('srlsinfo', 'Sandhill Regional Library System'),
('pasadena', 'Pasadena Public Library'),
('ccld', 'Cochise County Library District'),
('muskingum', 'Muskingum County Library System'),
('mln', 'Metro Library Network'),
('irclibrary', 'Indian River County Library'),
('stamford', 'The Ferguson Library'),
('yorkcountyva', 'York County Public Library'),
('griver', 'Great River Regional Library'),
('chesapeake', 'Chesapeake Public Library System'),
('slc', 'Suburban Library Cooperative'),
('chcbl', 'Chattanooga Public Library'),
('jclibrary', 'Jersey City Free Public Library'),
('fairfield', 'Fairfield Public Library'),
('pnm', 'National Library of Malaysia'),
('wplibs', 'Western Plains Library System'),
('livermore', 'Livermore Public Library'),
('southisland', 'South Island'),
('orlandparklibrary', 'Orland Park Public Library'),
('scl', 'Sunshine Coast Libraries'),
('newcanaanlibrary', 'New Canaan Library'),
('senecalibraries', 'Seneca District Libraries'),
('liverpool', 'Liverpool Libraries and Information Service'),
('fselibrary', 'Free State Public Library System'),
('cambridgeshirelibraries', 'Cambridgeshire County Council'),
('bibliotecascomfenalcoantioquia', 'Red de Bibliotecas de CCF Comfenalco Antioquia'),
('wtcpl', 'Warren-Trumbull County Public Library'),
('dorchesterlibrarysc', 'Dorchester County Library System'),
('pvld', 'Palos Verdes Library District'),
('ryutosho', 'Ryugasaki Public Library'),
('lubbock', 'Lubbock Public Library'),
('coqlibrary', 'Coquitlam Public Library'),
('myapl', 'Ascension Parish Library'),
('wbrl', 'Wood Buffalo Regional Library'),
('palsplus', 'PALS Plus NJ OverDrive Library'),
('westerncape', 'Western Cape Provincial Library'),
('georgesriver', 'Georges River Council Library'),
('manassasva', 'Manassas Park City Library'),
('edinburgh', 'Edinburgh Libraries'),
('bpls', 'Beaumont Public Library System'),
('tularecounty', 'Tulare County Library'),
('katrineholmsbibliotek', 'Katrineholms Bibliotek'),
('nioga', 'Nioga Library System'),
('act', 'Libraries ACT'),
('kanda-library', 'Kanda Town Library'),
('nilrc', 'NILRC Academic Shared Digital Collection'),
('lerum', 'Lerums Bibliotek'),
('richardson', 'Richardson Public Library'),
('cpcregional', 'Craven-Pamlico Regional Library'),
('northmankato', 'North Mankato Taylor Library'),
('sefl-municipal', 'Southeast Florida Library Association'),
('vikingdigitallibrary', 'Viking Library System'),
('cwcl', 'Uichang Library'),
('kfpl', 'Kingston Frontenac Public Library'),
('lccpl', 'Logansport-Cass County Public Library'),
('virtualmerri-bek', 'Merri-bek Libraries'),
('nnpls', 'Newport News Public Library System'),
('pickens', 'Pickens County Library System'),
('murraylibrary', 'Murray Library'),
('triparish', 'Tri-Parish E-Library'),
('portagelibrary', 'Portage County District Library'),
('cocolib', 'Flagstaff City-Coconino County Public Library'),
('stbbielefeld', 'Stadtbibliothek Bielefeld'),
('salon', 'Southern Adirondack Library System'),
('midland-mi', 'Grace A. Dow Memorial Library'),
('yamecity-lib', 'Yame City Library'),
('randolph', 'Randolph County Public Library'),
('fourcounty', 'Four County Library System'),
('torrance', 'Torrance Public Library'),
('rarakanra-library', 'Kanra Town Library'),
('ayase', 'Ayase Municipal Library'),
('palmspringslibrary', 'Palm Springs Public Library'),
('thehills', 'The Hills Library Service'),
('roundrock', 'Round Rock Public Library System'),
('norwalk', 'Norwalk Public Library'),
('collier', 'Collier County Public Library'),
('burbank', 'Burbank Public Library'),
('eastsussexlibrary', 'East Sussex County Council'),
('sanleandrolibrary', 'San Leandro Public Library'),
('winterparklibrary', 'Winter Park Public Library'),
('mymanatee', 'Manatee County Public Library System'),
('westsussexuk', 'West Sussex County Council'),
('lacnm', 'Los Alamos County Library System'),
('scw', 'Sun City West - R. H. Johnson Library'),
('alamancelibraries', 'Alamance County Public Libraries'),
('plymouthuk', 'Plymouth Library Services'),
('novel', 'Upper North Island'),
('stratford', 'Stratford Library Association'),
('canterburybankstownnsw', 'Canterbury-Bankstown Council'),
('krgnsw', 'Ku-ring-gai Library'),
('abilenetx', 'Abilene Public Library'),
('bnl', 'Bermuda National Library'),
('baycountylibrary', 'Bay County Library System'),
('calderdaleuk', 'Calderdale Council'),
('cumberland', 'Cumberland Council Libraries'),
('oilcreek', 'Oil Creek Library District'),
('kumagayacity', 'Kumagaya City Library'),
('westmoreland', 'Westmoreland eBook Network'),
('eastonpl', 'Easton Library District'),
('kurthmemorial', 'Kurth Memorial Library'),
('library-kiyose', 'Kiyose City Library'),
('bibliotecadigitalcompensar', 'Compensar'),
('peipls', 'Prince Edward Island Public Library Service'),
('richmondlibrary', 'Richmond Public Library'),
('gokatown-e-library', 'Goka Town Central Community Center Library'),
('bedfordshireuk', 'Bedford Borough and Central Bedfordshire'),
('lancasterlibraries', 'Library System of Lancaster County'),
('acld', 'Apache County Library District'),
('rlp', 'OverDrive Rheinland-Pfalz'),
('rbwm', 'Royal Borough of Windsor & Maidenhead'),
('claycofl', 'Clay County Public Library System'),
('pioneerland', 'Pioneerland Library System'),
('slolibrary', 'County of San Luis Obispo Public Libraries'),
('sequoyah', 'Sequoyah Regional Library System'),
('tds', 'Traverse des Sioux Library Cooperative'),
('wcdpl', 'Wood County District Public Library'),
('stclaircounty', 'Saint Clair County Library'),
('valnet', 'Valnet'),
('riopl', 'Rio Rancho Public Library'),
('mmpl', 'Moore Memorial Public Library'),
('southeasternok', 'Southeast Oklahoma Library System'),
('qroc', 'Queensland Regional OverDrive Consortium'),
('yukon', 'Yukon Public Libraries'),
('buenapark', 'Buena Park Library District'),
('thelosc', 'Libraries of Stevens County'),
('northyorks', 'North Yorkshire Libraries'),
('cityofsydney', 'City of Sydney Library Network'),
('rpl', 'Rapides Parish Library'),
('lambethuk', 'Lambeth Libraries'),
('northcountrylibraries', 'North Country Library System'),
('centralcoast', 'Central Coast Library Service'),
('cfwpl', 'Cedar Falls and Waterloo Public Libraries'),
('britanicolibrary', 'Británico Library'),
('lascruces', 'Las Cruces Public Libraries'),
('emcfl', 'Monterey County Free Libraries'),
('vdl', 'Valley Digital Library'),
('westleihe24', 'Westleihe24'),
('brimbanklibraries', 'Brimbank Libraries'),
('itako-public', 'Itako Public Library'),
('lbrut', 'London Borough of Richmond upon Thames'),
('cardiffuk', 'Cardiff Libraries'),
('detmold', 'Stadtbibliothek Detmold'),
('first', 'First Regional Library'),
('yoichi-library', 'Yoichi Town Library'),
('bportlibrary', 'Bridgeport Public Library'),
('nordleihe', 'Nordleihe'),
('elibrarybw', 'Büchereien Wien'),
('kuna', 'Kuna District Library'),
('newcastleau', 'Newcastle Region Library'),
('lltc', 'Little Libraries That Could'),
('mylakelibrary', 'Lake County Library System'),
('cclcvic', 'Connected Libraries'),
('cookmemorial', 'Cook Memorial Public Library'),
('erielibrary', 'Erie County Public Library'),
('lit', 'LIT Library'),
('bexley', 'London Borough of Bexley'),
('gptx', 'Grand Prairie Public Library System'),
('vapld', 'Vernon Area Public Library District'),
('ugc', 'Universidad La Gran Colombia'),
('colecciondigital', 'Biblioteca Pública Piloto de Medellín para América Latina'),
('midnorthcoast', 'Mid North Coast Library Service'),
('ipswichqld', 'Ipswich Libraries'),
('nwt', 'Northwest Territories Public Libraries'),
('emu', 'eMedien Unterfranken'),
('clcn', 'Capital Library'),
('cojlibrary', 'City of Johannesburg Library Services'),
('shioya-town-lib', 'Shioya Town Library'),
('hawkesbury', 'Hawkesbury Library Service'),
('zjlib', 'Zhejiang Library (浙江图书馆)'),
('sanfe', 'Santa Fe Public Library'),
('gcldaz', 'Gila County Library District'),
('randwick', 'Randwick City Library Services'),
('cityofdarwin', 'City of Darwin'),
('otofuke-library', 'Otofuke Town Library'),
('bocalibrary', 'Boca Raton Public Library'),
('waverley', 'Waverley Library'),
('melbournelib', 'City of Melbourne Libraries'),
('fclspa', 'Franklin County Library System'),
('medway', 'Medway Council'),
('maribyrnong', 'Maribyrnong Library Services'),
('city-susaki', 'Susaki City Library'),
('e-stockton', 'Stockton-on-Tees Libraries'),
('digibel', 'Busan English Library'),
('mcallen', 'McAllen Public Library'),
('rafbokasafnid', 'Rafbókasafnið'),
('sjrlc', 'South Jersey Regional Library Cooperative'),
('plumcreeklibrary', 'Plum Creek Library System'),
('akkeshi-town', 'Akkeshi Information Library'),
('woollahra', 'Woollahra Libraries'),
('highlandparktexas', 'Highland Park Library'),
('kuriyama-town', 'Kuriyama Town Library'),
('camdenlibrary', 'London Borough of Camden'),
('sanibel', 'Sanibel Public Library'),
('dscl', 'Dripping Springs Community Library'),
('mcls', 'Madison County Library System'),
('douglascpl', 'Douglas County Public Library'),
('prls', 'Parkland Regional Library'),
('westmount', 'Westmount Public Library'),
('geh-online', 'GEH-online'),
('portphillip', 'Port Phillip Library Service'),
('miracosta', 'MiraCosta College'),
('noosaqld', 'Noosa Library Service'),
('taipei', 'Taipei Public Library'),
('blacktown', 'Blacktown City Libraries'),
('waggin', 'Washington District Libraries'),
('indietexas', 'North Texas Independent Digital Consortium'),
('wirral', 'Wirral Libraries'),
('blackpool', 'Blackpool Libraries'),
('southtyneside', 'South Tyneside Libraries'),
('muenchen', 'Münchner Stadtbibliothek'),
('ceredigionuk', 'Ceredigion County Libraries'),
('yspubliclib', 'Songdo International Children''s Library'),
('elibrary247', 'eLibrary 24/7'),
('rivershare', 'RiverShare Library System'),
('yorklibraries', 'York Libraries'),
('reddecolombos', 'Colombian/American Bi-national Centers'),
('angusalive', 'Angus Alive'),
('swiss', 'EBOOKS SWITZERLAND'),
('douglasbcuk', 'Douglas Borough Council'),
('smsa', 'Sydney Mechanics'' School of Arts'),
('emagnolia', 'Magnolia eLibrary'),
('mediothek', 'Mediothek Krefeld'),
('isleofwightuk', 'Isle of Wight Library'),
('bnllux', 'National Library of Luxembourg'),
('claytonnc', 'Hocutt Ellington Memorial Library'),
('sbpl', 'San Bernardino Public Library'),
('renfrewshire', 'Renfrewshire Libraries'),
('warrenco', 'Warren County-Vicksburg Public Library'),
('jerseylibrary', 'States of Jersey'),
('hplct', 'Hartford Public Library'),
('rbpl', 'Redondo Beach Public Library'),
('byu', 'Brigham Young University'),
('helmet', 'Helsinki City Library'),
('yahabatown', 'Yahapark'),
('essexcountyuk', 'Essex County Library'),
('nu', 'Northwest University'),
('eausleihe-hannover', 'Stadtbibliothek Hannover'),
('perthandkinross', 'Culture Perth & Kinross Limited'),
('hubei', 'Hubei Provincial Library (湖北省图书馆)'),
('barnsley', 'Barnsley Libraries'),
('fundacionepm', 'Fundación EPM-Biblioteca EPM'),
('willoughbycc', 'Willoughby City Council'),
('islingtonuk', 'Islington Libraries'),
('fifeuk', 'Fife Libraries'),
('keskraamatukogu', 'Tallinn Central Library'),
('leedslibraryuk', 'Leeds Libraries'),
('staffordshireuk', 'Staffordshire County Council'),
('miltonkeynesuk', 'Milton Keynes Libraries'),
('highlanduk', 'Highland Libraries'),
('wexfordie', 'Wexford County Council Public Libraries'),
('frasercoast', 'Fraser Coast Regional Libraries'),
('seadl', 'Southeast Alabama Digital Library'),
('limerickie', 'Limerick City & County Library'),
('wiltshirelibsuk', 'Wiltshire Council Libraries'),
('bcsdmc', 'Bryan and College Station Public Library System'),
('mfo', 'Multinational Force and Observers'),
('coventrycityuk', 'Coventry City Library'),
('stirlinguk', 'Stirling Libraries'),
('fmb', 'Fort Myers Beach Public Library'),
('realtor', 'National Association of REALTORS®'),
('whittierpubliclibrary', 'Whittier Public Library'),
('sz', 'Shenzhen Library (深圳图书馆)'),
('sekicity', 'Seki City Library'),
('cefls', 'Clinton Essex Franklin Library System'),
('tztsg', 'Beijing Tongzhou District Library (北京市通州区图书馆)'),
('toowoombaqld', 'Toowoomba Region Libraries'),
('comfama', 'Comfama'),
('derbyshireuk', 'Derbyshire County Council'),
('rml', 'Rancho Mirage Public Library'),
('bremen', 'Stadtbibliothek Bremen'),
('tkpark', 'Thailand Knowledge Park'),
('sandoval', 'Sandoval County Library Consortium'),
('jscl', 'Jiangsu Children''s Digital Library (江苏省少儿数字图书馆)'),
('hoodcounty', 'Hood County Public Library'),
('jgrls', 'Jackson-George Regional Library System'),
('stlucieco', 'St. Lucie County Library System'),
('palmetto', 'Palmetto Library Consortium'),
('south-ayrshire', 'South Ayrshire Libraries'),
('lakemac', 'Lake Macquarie City Library'),
('brrl', 'Blue Ridge Regional Library'),
('duke', 'Duke University'),
('npl', 'Nacogdoches Public Library'),
('virtualbpld', 'Bartlett Public Library'),
('kings', 'Kings County Library'),
('brant', 'County of Brant Public Library'),
('frankston', 'Frankston City Libraries'),
('vppl', 'Virginia Piedmont Public Libraries'),
('santarosa', 'Santa Rosa County Library System'),
('listening-books', 'Listening Books'),
('baysidensw', 'Bayside Library NSW'),
('sdrcqld', 'Southern Downs Regional Council'),
('stuttgart', 'Stadtbibliothek Stuttgart'),
('chl', 'Central Highlands Regional Library'),
('hpulibraries', 'High Point University'),
('westberks', 'West Berkshire Libraries'),
('ocnc', 'Orange County Public Library'),
('baysidelibrary', 'Bayside Library Service'),
('centralwestzone', 'Central West Zone'),
('nottinghamshire', 'Nottinghamshire Libraries'),
('deichman', 'Oslo Public Library'),
('jessiehallett', 'Jessie F. Hallett Memorial Library'),
('milton', 'Milton Public Library'),
('abo', 'Akershus, Buskerud and Østfold County Library'),
('hempcolib', 'Hempstead County Library'),
('coffsharbour', 'Coffs Harbour Libraries'),
('navajoco', 'Navajo County Library District'),
('anan', 'Anan City Library'),
('northamptonshire', 'Northamptonshire Libraries and Information Services'),
('shetlanduk', 'Shetland Library'),
('mrl', 'Massanutten Regional Library'),
('xs', 'Beijing Xicheng Children''s Library (北京市西城区青少年儿童图书馆)'),
('gympie', 'Gympie Regional Libraries'),
('colbertdigitaldownloads', 'Colbert Digital Downloads'),
('ncgrl', 'Goldfields Libraries'),
('universityofminnesota', 'University of Minnesota'),
('aurauk', 'Aura Leisure and Libraries - Flintshire'),
('msl', 'Microsoft Library'),
('gatineauca', 'Gatineau Public Library'),
('trine', 'Trine University'),
('ebookssjclibrary', 'San Juan Community Library'),
('uj', 'University of Johannesburg'),
('mlpebooks', 'Mississippi eBook Library Partnership'),
('cod', 'College of DuPage'),
('zslib', 'Zhongshan Public Library (中山市中山图书馆)'),
('sh', 'Shanghai Library (上海图书馆)'),
('prairiestate', 'Prairie State College'),
('bilkent', 'Bilkent University Library'),
('alburycity', 'Albury City Library'),
('franken', 'OverDrive Verbund Franken'),
('cairnsqld', 'Cairns Libraries'),
('edlcuk', 'East Dunbartonshire Libraries'),
('northeaststate', 'Northeast State Community College'),
('hunterlibrariesgroup', 'Hunter Libraries Group'),
('gpls', 'Guam Public Library System'),
('leicestershire', 'Leicestershire Library Services'),
('swanseauk', 'Swansea Libraries'),
('crlnsw', 'Clarence Valley/Richmond Valley Libraries'),
('nwrl', 'Northwestern Regional Library'),
('vaudreuildorion', 'Bibliothèque de Vaudreuil-Dorion'),
('vcc', 'Vancouver Community College'),
('mackayqld', 'Mackay Libraries'),
('rtrlnsw', 'Richmond-Tweed Regional Library'),
('durango', 'Durango Public Library'),
('arl', 'Appalachian Regional Library'),
('cnlnsw', 'Central Northern Regional Library'),
('midcoastnsw', 'MidCoast Libraries'),
('umich', 'University of Michigan'),
('nwrlib', 'Northwest Regional Library System'),
('stokeontrentuk', 'Stoke on Trent Library'),
('livingstla', 'Livingston Parish Library'),
('townsvilleqld', 'Townsville Library Service'),
('banrepcultural', 'Biblioteca Luis Ángel Arango'),
('nacc', 'Northeast Alabama Community College'),
('cnelib', 'Chungcheongnam-do Library'),
('shorelinknsw', 'Shorelink Library Network'),
('greenwoodsc', 'Greenwood County Library System'),
('biberach', 'Stadtbücherei Biberach'),
('cpls', 'Coweta Public Library System'),
('iyte', 'Izmir Institute of High Technology'),
('sst', 'Shanghai Children''s Library (上海少年儿童图书馆)'),
('wellingtonvic', 'Wellington Shire Library Service'),
('valeofglamorgan', 'Vale of Glamorgan Libraries'),
('amc', 'US Embassy- Moscow American Center'),
('canterbury', 'Canterbury Christ Church University'),
('penang', 'Penang Digital Library'),
('niederrhein', 'Niederrhein'),
('yarralibraries', 'Yarra Libraries'),
('bmccnsw', 'Blue Mountains City Library Services'),
('azlibrary', 'Arizona State Library, Archives And Public Records'),
('hindmarsh', 'Hindmarsh Shire Libraries'),
('overdriveapi', 'OverDrive API Integration Library'),
('uniandes', 'Universidad de los Andes'),
('cachecounty', 'Cache County Library'),
('bookcloud', 'bookcloud'),
('fairfieldnsw', 'Fairfield City Open Libraries'),
('geelongvic', 'Geelong Regional Library'),
('disneytech', 'DPEP Tech & Digital Knowledge Center'),
('crsbpl', 'Books (Réseau BIBLIO)'),
('johnston', 'Johnston County Affiliated Libraries'),
('mi', 'Musicians Institute of Contemporary Music Los Angeles'),
('sejong', 'National Library of Korea - Sejong'),
('orpl', 'Oak Ridge Public Library'),
('altamonte', 'City of Altamonte Springs Library'),
('eastgippsland', 'East Gippsland Shire Library'),
('windsorca', 'Windsor Public Library'),
('reynoldslibraries', 'Reynolds Community College'),
('sandwelluk', 'Sandwell Libraries'),
('roscommonie', 'Roscommon County Library'),
('lclibs', 'Lebanon County Libraries'),
('carlowcounty', 'Carlow County Library'),
('svld', 'Smoky Valley Library District'),
('conestoga', 'Conestoga College'),
('abashiri-library', 'Abashiri City Library'),
('ahmlil', 'Arlington Heights Memorial Library'),
('bentleydownload', 'Bentley University'),
('kznpls', 'Kwa-Zulu Natal Provincial Library Services'),
('meltonvic', 'Melton Library & Learning Hub'),
('libriid', 'LIBRI System, Inc.'),
('gvrlc', 'Goulburn Valley Regional Library Corporation'),
('monlibvic', 'Monash Public Library Service'),
('pek', 'Pohjoisen eKirjasto'),
('bld', 'Beaumont Library District'),
('duesseldorf', 'Stadtbüchereien Düsseldorf'),
('wokinghamuk', 'Wokingham Libraries'),
('carmarthenshire', 'Carmarthenshire County Council'),
('westmeathie', 'Westmeath County Library'),
('wrexhamuk', 'Wrexham County Library'),
('newportuk', 'Newport City Council'),
('angleseyuk', 'Isle of Anglesey County Council - Llangefni Library'),
('awenculturaluk', 'Awen Cultural Trust'),
('gwynedduk', 'Gwynedd Libraries'),
('monmouthshire', 'Monmouthshire Libraries'),
('denbighshireuk', 'Denbighshire Libraries'),
('nptuk', 'Neath Port Talbot Libraries'),
('pembrokeshire', 'Pembrokeshire Libraries'),
('rctcbcuk', 'Rhondda-Cynon-Taf County Borough Libraries'),
('aneurinuk', 'Aneurin Leisure Trust'),
('caerphillyuk', 'Caerphilly Library Service'),
('torfaenuk', 'Torfaen County Borough Library'),
('merthyruk', 'Merthyr Libraries'),
('powysuk', 'Powys County Council'),
('latrobevic', 'Latrobe City Library'),
('conwyuk', 'Conwy Library & Information Service'),
('warwickshiregb', 'Warwickshire Library and Information Service'),
('rotorua', 'Rotorua Library'),
('phillipsburgnj', 'Phillipsburg Free Public Library'),
('ecpl', 'East Chicago Public Library'),
('wakefielduk', 'Wakefield Libraries and Information Services'),
('hamiltonnz', 'Hamilton City Libraries'),
('bw', 'Overdrive Baden-Württemberg'),
('guernseypublic', 'Guernsey Public Library'),
('nambucca', 'Nambucca Valley Council Libraries'),
('mornpen', 'Mornington Peninsula Libraries'),
('bibliobrossard', 'Bibliotheque de Brossard'),
('dublincityie', 'Dublin City Libraries'),
('kilkennyie', 'Kilkenny County Library'),
('fingalcountyie', 'Fingal County Library'),
('corkcountyie', 'Cork County Library'),
('galwayie', 'Galway Public Library'),
('monaghanie', 'Monaghan County Libraries'),
('clarecounty', 'Clare County Library'),
('cavancounty', 'Cavan County Libraries'),
('longfordcounty', 'Longford County Library'),
('donegalcountyie', 'Donegal County Library'),
('leitrimcountyie', 'Leitrim County Library'),
('kerryie', 'Kerry Library'),
('sligocountyie', 'Sligo County Council'),
('louthcounty', 'Louth County Library'),
('southdublinie', 'South Dublin Libraries'),
('meathcountyie', 'Meath County Library'),
('tipperaryie', 'Tipperary Public Library'),
('mayocountyie', 'Mayo County Library'),
('offalycountyie', 'Offaly County Library'),
('waterfordlib', 'Waterford City & County Libraries'),
('wicklowie', 'Wicklow County Library'),
('laoiscountyie', 'Laois County Library'),
('kildareie', 'Kildare County Council Library and Arts Service'),
('corkcityie', 'Cork City Library'),
('eastayrshireuk', 'East Ayrshire Libraries'),
('solihulluk', 'Solihull Metropolitan Borough Council'),
('nottinghamcity', 'Nottingham City Libraries'),
('coventry', 'Coventry Public Library'),
('biblioquebec', 'Magazines (Réseau BIBLIO)'),
('onomichi-city', 'Onomichi City Library'),
('pura', 'Zentralbibliothek PURA'),
('kaust', 'KAUST'),
('rutlanduk', 'Rutland Library Service'),
('derbycitygb', 'Derby City Council'),
('cheshire', 'Cheshire Libraries'),
('gplebooks', 'Gary Public Library'),
('cne-siar', 'Western Isles Libraries'),
('dls', 'Defence Library Service'),
('zulabryantwylie', 'Zula Bryant Wylie Library'),
('uwisconsin', 'University of Wisconsin System'),
('tamus', 'Texas A&M University System Libraries'),
('nblib', 'Ningbo Library (宁波图书馆)'),
('telford', 'Telford & Wrekin Libraries'),
('simbacqlm', 'Réseau BIBLIO CQLM'),
('uwashington', 'University of Washington'),
('gatech', 'Georgia Tech Library'),
('gifucity-d-library', 'Gifu City Library'),
('hzlib', 'Hangzhou Public Library (杭州图书馆)'),
('middletown', 'Middletown Public Library'),
('barrielibrary', 'Barrie Public Library'),
('librarieswestuk', 'Libraries West'),
('v3r', 'Bibliotheques de Trois-Rivieres'),
('westcaldwellnj', 'West Caldwell Public Library'),
('unisabana', 'Universidad de la Sabana'),
('danburylibrary', 'Danbury Public Library'),
('mslsau', 'Mitchell Shire Library Service'),
('middleburypubliclibrary', 'Middlebury Public Library'),
('notlpubliclibrary', 'Niagara-on-the-Lake Public Library'),
('bibliomontmagny', 'Bibliotheque de Montmagny'),
('stavanger', 'Sølvberget bibliotek og kulturhus'),
('bibliothequesdesherbrooke', 'Les Bibliothèques de Sherbrooke'),
('rubysisson', 'Upper San Juan Library District'),
('meridianlauderdale', 'Meridian-Lauderdale County Public Library'),
('ngrls', 'Northwest Georgia Regional Library System'),
('essexuni', 'The University of Essex'),
('omia', 'OverDrive for Michigan Academics'),
('seoullib', 'Seoul Metropolitan Library'),
('simba2', 'Réseau BIBLIO de la Montérégie'),
('trondelag', 'Trøndelag'),
('readinguk', 'Reading Libraries'),
('vaski', 'Vaski/Turku City Library'),
('yonginlib', 'YongIn City Library'),
('yale', 'Yale University'),
('jaqtsg', 'Jing''an District Library (上海市静安区图书馆)'),
('odl', 'Oklahoma Department of Libraries'),
('kindai', 'Kindai University'),
('osnabrueck', 'Stadtbibliothek Osnabrück'),
('koeln', 'Stadtbibliothek Köln'),
('kingstonvic', 'Kingston Libraries'),
('downbeach', 'Longport Public Library'),
('martinluther', 'Martin Luther College'),
('jf', 'The Japan Foundation'),
('nnyoverdrive', 'Northern New York Library Network'),
('falkirkuk', 'Falkirk Libraries'),
('lasalle', 'Lasalle Parish Library'),
('enalis', 'National Library and Information System Authority'),
('usu', 'Utah State University'),
('campaspe', 'Shire of Campaspe'),
('elprlibrary', 'Lonesome Pine Regional Library'),
('e-thek', 'e-Thek'),
('clarendoncountylibrary', 'Harvin Clarendon County Library'),
('szlib', 'Suzhou Library (苏州图书馆)'),
('pajulib', 'Paju Hanbit Library'),
('mpkdigital', 'Moorpark City Library'),
('emory', 'Emory University'),
('nhfpl', 'New Haven Free Public Library'),
('dogoklib', 'Dogok Library'),
('ccfls', 'Crawford County Federated Library System'),
('piki', 'PIKI Libraries'),
('dorval', 'Dorval Library'),
('ppas', 'Perbadanan Perpustakaan Awam Selangor'),
('seagirtnj', 'Sea Girt Public Library'),
('musselmanlibrary', 'Gettysburg College'),
('jhlibrary', 'Jackson/Hinds Library System'),
('egfmn', 'East Grand Forks-Campbell Library'),
('eastridinguk', 'East Riding Libraries'),
('apl', 'Anseong-si Public Library'),
('e-medien-franken', 'eMedien Franken'),
('easterncape', 'Eastern Cape Provincial Library Service'),
('accairo', 'American Center Cairo - US Embassy Egypt'),
('stonington', 'Stonington Free Library'),
('bc', 'Boston College'),
('ebooksforyou', 'eBooks for You'),
('morgancitylibrary', 'Morgan City Public Library'),
('cs', 'Changsha Library (长沙图书馆)'),
('wzlib', 'Wenzhou Library (温州市图书馆)'),
('stadtbibliothek-leipzig', 'Leipziger Stadtbibliothek'),
('jplmontreal', 'Jewish Public Library'),
('blackfoot', 'Blackfoot Public Library'),
('bibliotecascomfamiliar', 'Comfamiliar Risaralda'),
('aenetworks', 'A&E Televison Networks'),
('azwestern-library', 'Arizona Western College'),
('unimelb', 'University of Melbourne Student Union'),
('southwestfl', 'Southwest Florida Library Network'),
('lancashireuk', 'Lancashire County Library and Information Service'),
('childrens', 'Children''s Medical Center'),
('tvcc', 'Trinity Valley Community College'),
('asfmrc', 'Archdiocese of Santa Fe'),
('hamiltondigitallibrary', 'Hamilton Digital Library'),
('morrin', 'Morrin Centre Library'),
('uis', 'Universidad Industrial de Santander'),
('elin', 'Estacado Library Information Network'),
('braunschweig', 'Stadtbibliothek Braunschweig'),
('dorsetuk', 'Dorset Libraries'),
('stadtbibliothek-graz', 'Stadtbibliothek Graz'),
('s-h', 'OverDrive Schleswig-Holstein'),
('tateyama-city', 'Tateyama Municipal Library'),
('longleaf', 'Longleaf Library Consortium'),
('bostonunbanned', 'Books Unbanned - Boston Public Library'),
('hindscc', 'Hinds Community College'),
('libertyuniversity', 'Liberty University'),
('atwaterlibrary', 'Atwater Library and Computer Centre'),
('hcln', 'High Country Library Network'),
('ucb', 'University of California Berkeley'),
('whitsundayrc', 'Whitsunday Regional Council Library Service'),
('wiscal', 'Wisconsin Academic Library Consortium'),
('ucirvinemain', 'University of California Irvine'),
('overdrivegerman', 'OverDrive Library Demo Germany'),
('imperial', 'Imperial College, London'),
('huie', 'Henderson State University, Huie Library'),
('saxtonblittle', 'Saxton B. Little Free Library'),
('bbfmonterrey', 'Biblioteca Benjamin Franklin de Monterrey'),
('hillingdonuk', 'London Borough of Hillingdon Libraries'),
('nuqlibrary', 'Northwestern University in Qatar'),
('uofmiami', 'University of Miami Libraries'),
('lpclibrary', 'Las Positas College'),
('obrienmemoriallibrary', 'O''Brien Memorial Library'),
('paderborn', 'Stadtbibliothek Paderborn'),
('mercantile', 'The Mercantile Library'),
('maderalibrary', 'Madera County Library'),
('fjclib', 'Fujian Juvenile & Children''s Library'),
('ucmmo', 'University of Central Missouri'),
('wuppertal', 'Stadtbibliothek Wuppertal'),
('vccs', 'Virginia Community College System'),
('pettes', 'Pettes Memorial Library'),
('clevelandfbc', 'First Baptist Cleveland Church Library'),
('kmclib', 'Kunming Children''s Library (昆明少年儿童图书馆)'),
('wvu', 'West Virginia University'),
('cornell', 'Cornell University Library'),
('jsou', 'Joint Special Operations University'),
('jxlib', 'Jiaxing Library (嘉兴市图书馆)'),
('boisestate', 'Boise State University Albertsons Library'),
('pentagonlib', 'Pentagon Library'),
('northwestlib', 'North West Provincial Library Services'),
('bibstlaz', 'Saint-Lazare Library'),
('eunc', 'European Nazarene College'),
('hancockcollege', 'Allan Hancock Community College'),
('bibliotecauao', 'Universidad Autónoma de Occidente'),
('guetersloh', 'Stadtbibliothek Gütersloh'),
('pokagon', 'Pokagon Tribal Library'),
('ncbi', 'National Council for the Blind of Ireland'),
('mbts', 'Midwestern Baptist Theological Seminary'),
('ricepubliclibrary', 'Rice Public Library'),
('com', 'College of the Mainland'),
('pcc', 'Portland Community College'),
('bcpcounciluk', 'Bournemouth, Christchurch and Poole Council (BCP)'),
('seocholib', 'Seocho Library'),
('city', 'City, University of London'),
('willowbrookbaptist', 'Willowbrook Baptist Church'),
('sloughuk', 'Slough Libraries'),
('wflib', 'Weifang Library (潍坊市图书馆)'),
('karlsruhe', 'Stadtbibliothek Karlsruhe'),
('cloviscollegeca', 'Clovis Community College'),
('nyjlib', 'Namyangju-si Library'),
('cyberlibrary', 'Gyeonggi-do Cyber Library'),
('georgiahighlands', 'Georgia Highlands College'),
('seynatlib', 'Seychelles National Library'),
('darlingtonuk', 'Darlington Libraries'),
('interlinklibraries', 'Public Library InterLINK - Restricted to Print Disabled Patrons'),
('northeasternuni', 'Northeastern University'),
('bibliounicosta', 'Universidad de la Costa'),
('marylanddcdl', 'Maryland Deaf Culture Digital Library'),
('mnstate', 'Minnesota State University, Moorhead'),
('holmeslibrary', 'Holmes Community College'),
('stadtbuechereimuenster', 'Stadtbücherei Münster'),
('slb-potsdam', 'Stadt- und Landesbibliothek Potsdam'),
('illinoislibrary', 'University of Illinois'),
('onchan', 'Onchan Public Library'),
('tibet', 'Tibet Library'),
('queerliblib', 'Queer Liberation Library'),
('ssllib', 'Songshan Lake Library'),
('southamptonuk', 'Southampton City Libraries'),
('rpidrs', 'Religionspädagogische Institute der Diözese Rottenburg-Stuttgart'),
('hertfordshireuk', 'Hertfordshire Libraries'),
('ced', 'North Carolina State University - College of Education'),
('kennebunklibrary', 'Kennebunk Free Library'),
('fbi', 'Federal Bureau of Investigation Library'),
('longwood', 'Longwood University'),
('quatrefoil', 'Quatrefoil Library'),
('poetrylibrary', 'Southbank Centre'),
('uai', 'Universidad Adolfo Ibañez'),
('pforzheim', 'Stadtbibliothek Pforzheim'),
('halle', 'Stadtbibliothek Halle'),
('vsulibrary', 'Virginia State University'),
('jhlib', 'Wuhan Jianghan District Library'),
('candid', 'Candid'),
('manno', 'Manno Town Library'),
('circulodeafiliadosccb', 'Camara de Comercio de Bogota'),
('mottlibrary', 'Mott Community College'),
('exeteruk', 'University of Exeter'),
('rooseveltvirtual', 'Biblioteca Roosevelt (Centro Cultural Paraguayo Americano)'),
('htu', 'Huston-Tillotson University'),
('kplonline', 'Kigali Public Library'),
('fba', 'First Baptist Church of Atlanta'),
('md', 'Stadtbibliothek Magdeburg'),
('lti', 'Literature Translation Institute of Korea'),
('noaalibs', 'NOAA Library Network'),
('hacc', 'Harrisburg Area Community College'),
('jccgv', 'Isaac Waldman Jewish Public Library'),
('hccc', 'Hudson County Community College'),
('rcsi-mub', 'RCSI- Medical University of Bahrain'),
('jcjc', 'Jones County Junior College'),
('calstatelb', 'California State University-Long Beach'),
('dortmund', 'Stadt- und Landesbibliothek Dortmund'),
('lehigh', 'Lehigh University'),
('ciu', 'Columbia International University'),
('walsalluk', 'Walsall Libraries'),
('colombianlib', 'OverDrive Library Marketplace Demo - Colombia (CO)'),
('luzerne', 'Luzerne County Community College'),
('lakeareatech', 'Lake Area Technical College'),
('txstate', 'Texas State University-San Marcos'),
('charteredaccountantsanz', 'Chartered Accountants Australia and New Zealand'),
('interchurchcenter', 'Interchurch Center'),
('cwsl', 'California Western School of Law'),
('middlebury', 'Middlebury College'),
('bgst', 'Biblical Graduate School of Theology'),
('falklandcommunitylibrary', 'Falkland Community Library'),
('californiajewishlibraries', 'California Jewish Library Digital Book Consortium'),
('hulluni', 'University of Hull'),
('sthelensuk', 'St. Helens Library Service'),
('roberts', 'Roberts Wesleyan College & Northeastern Seminary'),
('icanabcl', 'ICANA - el Centro Binacional (American Spaces)'),
('lafayette', 'Lafayette College'),
('nic', 'National Institute of Corrections'),
('salb', 'South African Library for the Blind'),
('dementia-e-library', 'Dementia Australia Library'),
('bibliotecafundadores', 'Universidad CES'),
('bangorpl', 'Bangor Public Library'),
('accenture', 'Accenture Solutions Private Limited'),
('swarthmore', 'Swarthmore College'),
('uhnpatient', 'University Health Network'),
('stanford', 'Stanford University'),
('stockportgb', 'Stockport Libraries, Information, Advice'),
('dakotastate', 'Dakota State University'),
('aidecanada', 'AIDE Canada'),
('librarynetwork', 'World Bank International Monetary Fund Library Network'),
('tbpl', 'Thunder Bay Public Library'),
('bloomberg', 'Bloomberg Finance L.P.'),
('denverseminary', 'Denver Seminary'),
('ccnn', 'Centro Cultural Nicaraguense Norteamericano'),
('ichikawaekinan', 'Ichikawa City Ichikawa Station South Gate Library (Viax)'),
('vtlibraries', 'Vermont Department Of Libraries'),
('paclibrary', 'Palo Alto College'),
('mainehealthlrc', 'MaineHealth Learning Resource Center'),
('librarybrunei', 'Perpustakaan Dewan Bahasa dan Pustaka Brunei'),
('roeuni', 'University of Roehampton London'),
('neo', 'NEO A&M College'),
('boniuklibrary', 'Holocaust Museum Houston, Boniuk Library'),
('nihlibrary', 'National Institutes of Health Library'),
('ccri', 'Community College of Rhode Island'),
('orparc', 'Oregon Post Adoption Resource Center'),
('rmccanada', 'Royal Military College of Canada'),
('southendonseauk', 'Southend-on-Sea Libraries'),
('mtsu', 'Middle Tennessee State University'),
('commerceresearchlibrary', 'Commerce Research Library'),
('weizmann', 'The Weizmann Institute of Science'),
('gia', 'Gemological Institute of America'),
('ochsner', 'Ochsner Medical Library'),
('bristollibraries', 'Bristol Libraries'),
('cass', 'Chinese Academy of Social Sciences'),
('cusm', 'McGill University Health Centre'),
('pepperdine', 'Pepperdine University Libraries'),
('rhslibraries', 'The Royal Horticultural Society'),
('bibliotecaargos', 'Argos'),
('trinitylibrary', 'Trinity Washington University'),
('statelibks', 'State Library of Kansas'),
('nachikatsuuratown', 'Nachikatsuura Town Board of Education'),
('tamesideuk', 'Tameside Libraries'),
('oldtownpub', 'Old Town Public Library'),
('ssw', 'Seminary of the Southwest'),
('manchestergb', 'Manchester Public Library'),
('meridiancc', 'Meridian Community College'),
('coa', 'College of Alameda'),
('goucherlibrary', 'Goucher College Library'),
('pit', 'Pennsylvania Institute of Technology'),
('hamiltondiocesebfl', 'Bishop Farrell Library'),
('northamptonpa', 'Northampton Area Public Library'),
('jamestownri', 'Jamestown Philomenian Library'),
('oldhamgb', 'Oldham Libraries'),
('midlothianlibuk', 'Midlothian Council Library Service'),
('nsftlibrary', 'Norfolk and Suffolk NHS Foundation Trust'),
('biddlelaw', 'University of Pennsylvania Law Library'),
('sandiegochristian', 'San Diego Christian College'),
('epannapolis', 'Evangelical Presbyterian Church'),
('bathnesuk', 'Bath & North East Somerset Libraries'),
('northsomersetuk', 'North Somerset'),
('southglosuk', 'South Gloucestershire Libraries'),
('somersetuk', 'Somerset Library'),
('salforduk', 'Salford Libraries'),
('faithmc', 'Faith Methodist Church Singapore'),
('universityvt', 'University of Vermont'),
('lruffin-smith', 'Cleveland Clinic Lou Ruvo Center for Brain Health'),
('cuboulder', 'University of Colorado Boulder'),
('usturkmenistan', 'U.S. Embassy Ashgabat'),
('iue', 'Institución Universitaria de Envigado - IUE'),
('upsem', 'Union Presbyterian Seminary'),
('newrelic', 'New Relic'),
('levine-sklutjudaiclibrary', 'Center For Jewish Education / Levine Sklut Judaic Library'),
('oronome', 'Orono Public Library'),
('csusm', 'California State University-San Marcos'),
('utltoronto', 'University of Toronto'),
('bergencc', 'Bergen Community College'),
('card', 'Center for Autism and Related Disabilities'),
('humber', 'Humber College'),
('eblink', 'eBLINK'),
('ivanlibrary', 'Ivan the Terrier, Inc.'),
('uhmanoa', 'University of Hawaii at Manoa'),
('sqcc', 'Sultan Qaboos Cultural Center'),
('samsung', 'Samsung Electronics UK'),
('sjc', 'St James'' Church, Singapore'),
('philanthropysoutheast', 'Philanthropy Southeast'),
('thurrockuk', 'Thurrock Library Service'),
('dumgaluk', 'Dumfries & Galloway Libraries'),
('durhamcountyuk', 'Durham County Council'),
('rochdaleuk', 'Rochdale Libraries'),
('boltonuk', 'Bolton Libraries'),
('burycounciluk', 'Bury Council Libraries'),
('wiganuk', 'Wigan Libraries'),
('westlothianuk', 'West Lothian Libraries'),
('traffordgb', 'Trafford Libraries'),
('blackburnuk', 'Blackburn with Darwen Library & Information Services'),
('hrh', 'Humber River Hospital'),
('austincollege', 'Austin College'),
('wscclibrary', 'Wallace State Community College-Hanceville'),
('mercerebooks', 'Mercer School'),
('jfcsholocaustcenter', 'JFCS Holocaust Center'),
('iona', 'Iona University'),
('bruneluniversity', 'Brunel University'),
('nulibrary', 'Nazarbayev University'),
('drakestate', 'Drake State Community and Technical College'),
('glosuk', 'Gloucestershire Libraries'),
('stevenson', 'Stevenson University'),
('hamline', 'Hamline University'),
('kcl', 'King''s College London'),
('newhope', 'New Hope Presbyterian Church'),
('stadtbibliotheksalzburg', 'Stadtbibliothek Salzburg'),
('queenstheology', 'Queens College Of Theology'),
('aialouisiana', 'The American Institute of Architects Louisiana AIA Louisiana'),
('crossroadshospice', 'Crossroads Hospice Society'),
('harrisonco', 'Harrison County Library System'),
('1stsfgroup', '1SFG (A)'),
('dgcbc', 'Directors Guild of Canada, British Columbia'),
('caltech', 'California Institute of Technology'),
('siskiyous', 'College of the Siskiyous'),
('mesalands', 'Mesalands Community College'),
('dal', 'Dalhousie University Killam Library'),
('ucn', 'University College of the North'),
('lgt', 'Lewisham and Greenwich NHS Trust'),
('colostate', 'Colorado State University-Fort Collins'),
('ptbolibrary', 'Peterborough Public Library'),
('kawarthalakes', 'City of Kawartha Lakes Public Library'),
('cumberlandri', 'Cumberland Public Library'),
('mbkohio', 'MBK Ohio'),
('eprovidenceri', 'East Providence Public Library'),
('hoperi', 'Hope Library'),
('westdunbartonuk', 'West Dunbartonshire Libraries'),
('northsmithfield', 'North Smithfield Public Library'),
('chelsea', 'Chelsea Library'),
('nmbm', 'Nelson Mandela Bay Municipality'),
('japanhousela', 'Japan House Los Angeles'),
('seftonuk', 'Sefton Libraries'),
('bayouland', 'Bayouland E-Library Co-Op'),
('teshiotown', 'Teshio Town Social Welfare Center Library'),
('hampshireuk', 'Hampshire Libraries'),
('acphslibrary', 'Albany College of Pharmacy and Health Sciences'),
('librariesunlimited', 'Libraries Unlimited'),
('saginawlibrary', 'Public Libraries of Saginaw'),
('worcesteruk', 'Worcestershire County Libraries'),
('kcpl', 'Knox County Public Library'),
('mercercountycommunitycollege', 'Mercer County Community College'),
('viken', 'Viken Fylkesbibliotek'),
('manchestercc', 'Manchester Community College'),
('kleberglibrary', 'Robert J. Kleberg Public Library'),
('bluehill', 'Blue Hill Public Library'),
('uilib', 'Uijeongbu Library'),
('clemson', 'Clemson University'),
('sashlibrary', 'Surrey and Sussex Healthcare'),
('beaverco', 'Beaver County Library System'),
('darebinlib', 'Darebin Libraries'),
('friendmemorial', 'Friend Memorial Library'),
('southeastzone', 'South East Zone'),
('cumbriauk', 'Cumberland and Westmorland and Furness Libraries'),
('northlanarkshire', 'North Lanarkshire Libraries'),
('herricklibrary', 'Herrick Community Health Care Library'),
('sunderlanduk', 'Sunderland Libraries Services'),
('newcastlelibsuk', 'Newcastle Libraries'),
('soracomics', 'Sora Comics'),
('camdennsw', 'Camden Council Library Service'),
('iedigital', 'Riverside County Library System'),
('dcsre-mplis', 'Mpumalanga Library and Information Service'),
('rockhampton', 'Rockhampton Regional Library Services'),
('gladstonelib', 'Gladstone Regional Libraires'),
('livingstone', 'Livingstone Shire Library Service'),
('slanarkshire', 'South Lanarkshire Libraries'),
('dscc', 'Dyersburg State Community College'),
('gauteng', 'Gauteng Provincial Library Service'),
('hobsonsbayvic', 'Hobsons Bay Libraries'),
('gleneira', 'Glen Eira Libraries'),
('nyackats', 'Nyack College'),
('southwestzone', 'South West Zone'),
('sjstsg', 'Library of Shijingshan District (石景山区图书馆)'),
('bibnetz', 'Verbund Bibnetz'),
('wyndhamvic', 'Wyndham City Libraries'),
('humecity', 'Hume Libraries'),
('corangamite', 'Corangamite Moyne Library Service'),
('chrclib', 'Central Highlands Regional Council Library Services'),
('haringey', 'London Borough of Haringey'),
('doncasterlibraries', 'Doncaster Libraries'),
('bundabergqld', 'Bundaberg Regional Library'),
('betterhealthlibrary', 'Better Health Library'),
('swindonuk', 'Swindon Borough Council');